### ISSUE TITLE
/list feature

### ISSUE THREAD

**Issue by becdot** [mtthwhggns/tomatobot#26]
I'd love to see a slack feature where you could list the things that you want to work on that day, and then maybe you could select things from that list when you go to "/startwork".  This would be a nice way to organize thoughts, and then it could be helpful when "/review"ing the list of things that you worked on the day previous.

**Comment by mtthwhggns** [comment]
This is an interesting idea Becca! 

I like the idea, especially considering comparing completed tasks with planned tasks.

My issue is that I'm trying to avoid this becoming a "to-do list" type of app. The pomodoro technique is about getting stuff done, but not necessarily one thing per pomodoro. It's quite OK to do three things on one pomodoro (that's why `/completed` can accept many things) or for one thing to take several pomodoros.

For me, in how I work, Pomodoro is about focusing intensely for 25 minutes while trying to eliminate distractions, then taking a break to make sure I don't lose focus, rather than about tracking exactly which items from my plan got done (there are other systems for that, that can be used alongside the pomodoro technique). 

@becdot Can you think of a way to track "things I'd like to do" alongside "how well I'm focusing"? If you can, I'd be up for trying to implement this!

**Comment by johanbove** [comment]
> My issue is that I'm trying to avoid this becoming a "to-do list" type of app.

I concur to that. Pomodoro is about focus as you said.
