### ISSUE TITLE
Time Breaks?

### ISSUE THREAD

**Issue by jamescgibson** [mtthwhggns/tomatobot#36]
I LOVE tomatobot! First time I've ever had pomodoro method really stick. 

I'd love it if it could time my breaks too. I understand via Twitter that there's an API issue here; I'm not experineced writing slack integrations, but if I could get a quick intro to the issue, I would be happy to try to find a workaround.

**Comment by mtthwhggns** [comment]
The issue, at the moment, is that a 25 minute Pomodoro is usually flooded by a 5, sometimes a 20 minute break, but the Slack API only allows messages in response to a slash command for 30 minutes after the initial command, so, if we time it accurately, it will have exceeded that window when the "end of break" message is sent, for both 5 and 20 minute breaks.

There are two alternatives I can see;
- A separate, "time break" command. This would work and be quite easy to implement. The problem is that Slack have already told me they would prefer to reduce the number of different commands per integration, and to ideally get everything under a single `/tomatobot` or `/tb` command. 
- Once we get everything under a single command, we could have a workflow like this;

> tb: You've finished your pomodoro, time for a 5 minute break! Would you like me to time it?
> user: /tb yes
> tb: Starting your break now
> ...
> tb: That's the end of your break. Are you ready to start your next Pomodoro?
> user: /tb yes

And so on.

The second option is my preference. I'll probably start migrating to a single command quite soon, and run them side-by-side for a little while, as it fits in better with how many other integrations work.

**Comment by jamescgibson** [comment]
Gotcha. I think the "yes" would work great.

**Comment by lshearer** [comment]
Perhaps the new [interactive buttons](https://api.slack.com/docs/message-buttons) would be nice for something like responding to the timer question.

**Comment by mtthwhggns** [comment]
@lshearer That's the plan, and I'll give it a try (I'm not sure if there will be time to get it all implemented though) this weekend!
