### ISSUE TITLE
Add option for visible pomodora, for entire channel

### ISSUE THREAD

**Issue by gatesyp** [mtthwhggns/tomatobot#50]
As far as I can see, creating a new timer via /startwork creates one timer which is only visible and accessible to the user who input the command. 

I've noticed that in teams I work in, we use one timer for the entire group - that way our breaks are synced up, and everyone is quiet at the same times as well. 

It'd be great to have the option of creating a public timer which is visible to the channel. Basically mirroring all the functionality you have for individuals, but making it public and only allowing one instance of the public timer (exactly how it is for private).

**Comment by mtthwhggns** [comment]
I've been thinking about this, as it's not the first time it's been requested.

It's a lot of work, as currently, everything is tied to a user, rather than a team or a channel.

One thing that would be fairly simple to implement would be a `public` keyword, just like `/review` has at the moment, for any command, so you can share all of the commands, not just the review. 

I propose that I implement this quite soon, and we wait and see how popular it is. If it gets some use, I'd be happy to look into the bigger part of this idea. 

What do you think?

**Comment by gatesyp** [comment]
I love the public keyword idea - that's more along the lines of how I was thinking. It could be pretty cheap to implement. 

Thanks for being receptive to the idea!

**Comment by mtthwhggns** [comment]
The public keyword feature is deployed now.
