### ISSUE TITLE
Use a separate bullet for each completed task when using /review

### ISSUE THREAD

**Issue by mgrosman** [mtthwhggns/tomatobot#59]
Currently multiple completed items are just grouped together in a single paragraph, joined by "and", which doesn't make it easy to see each individual item. Would be great to break each completed task to a separate bullet so easier to take at a glance.

Also when I try to review past completed tasks (say for yesterday) I only get the first item.

**Comment by mtthwhggns** [comment]
The bullet points are per "work period" rather than per task, so you can see "in my first 25 minutes, I did Task A, Task B and Task C, and in my second 25 minutes, I did Task D and Task E". So this is very much by design. 

Regarding the second point, can you create a separate issue with the steps to replicate, and I'll try and look into it? I've not been able to replicate it after a quick look.
